import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Upload as UploadIcon, Video, FileVideo, Sparkles } from 'lucide-react'
import { UploadForm } from '@/components/upload/upload-form'
import { getCurrentCreator } from '@/lib/db/creator'
import Link from 'next/link'

// Force dynamic rendering - this page uses searchParams
export const dynamic = 'force-dynamic'

export default async function UploadPage({
  searchParams,
}: {
  searchParams?: Promise<{ profile?: string }> | { profile?: string }
}) {
  // Handle searchParams (might be Promise in newer Next.js)
  const params = searchParams instanceof Promise ? await searchParams : searchParams
  
  let creator = null
  try {
    creator = await getCurrentCreator(params?.profile)
  } catch (error: any) {
    console.error('[UploadPage] Error fetching creator:', error?.message || String(error))
  }

  if (!creator) {
    return (
      <div className="space-y-8">
        <div>
          <h1 className="text-4xl font-extrabold mb-3">Upload Content</h1>
          <p className="text-foreground/80 text-lg font-medium">
            Please complete your creator profile first.
          </p>
        </div>
        <Card className="border-primary/30 bg-card-elevated">
          <CardContent className="pt-6">
            <div className="text-center py-8">
              <p className="text-lg font-semibold mb-4 text-foreground/90">
                Complete your creator profile to start uploading content.
              </p>
              <Link href="/setup">
                <Button size="lg" className="bg-primary hover:bg-primary-dark">
                  Set Up Profile
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-8">
      <div className="mb-8">
        <h1 className="text-4xl font-extrabold mb-3">Upload Content</h1>
        <p className="text-foreground/80 text-lg font-medium">
          Upload UGC content or manage AI-generated content from AIR Ideas
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        {/* UGC Upload */}
        <Card>
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="p-2 bg-primary/20 rounded-lg">
                <FileVideo className="h-6 w-6 text-primary" />
              </div>
              <div>
                <CardTitle>Upload UGC Content</CardTitle>
                <CardDescription>
                  Upload your own video content
                </CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <UploadForm creatorUniqueIdentifier={creator.unique_identifier} />
          </CardContent>
        </Card>

        {/* AI-Generated Content */}
        <Card>
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="p-2 bg-primary/20 rounded-lg">
                <Sparkles className="h-6 w-6 text-primary" />
              </div>
              <div>
                <CardTitle>AI-Generated Content</CardTitle>
                <CardDescription>
                  Manage content from AIR Ideas
                </CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <p className="text-sm text-foreground/70">
                Content generated by AIR Ideas will automatically appear here as
                drafts. You can edit, schedule, or publish them directly.
              </p>
              <Button variant="outline" className="w-full">
                View AI Drafts
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Upload Guidelines */}
      <Card>
        <CardHeader>
          <CardTitle>Upload Guidelines</CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2 text-sm text-foreground/70">
            <li>• Supported formats: MP4, MOV, AVI (max 500MB)</li>
            <li>• Recommended resolution: 1080p or higher</li>
            <li>• Add a compelling title and description for better performance</li>
            <li>• Select the target platform before scheduling</li>
            <li>• Thumbnails are automatically generated but can be customized</li>
          </ul>
        </CardContent>
      </Card>
    </div>
  )
}

