-- Migration: Fix airpublisher_creator_profiles schema
-- Ensures handles and profile_pic_url columns exist
-- Removes Niche column (niche should come from creator_profiles/shared schema)
-- Fixes creator_unique_identifier NOT NULL constraint issue

-- Step 1: Drop the foreign key constraint to creator_profiles
-- airpublisher_creator_profiles can exist independently (no need to link to creator_profiles)
ALTER TABLE airpublisher_creator_profiles
DROP CONSTRAINT IF EXISTS airpublisher_creator_profiles_creator_unique_identifier_fkey;

-- Step 2: Make creator_unique_identifier nullable (trigger will generate it)
ALTER TABLE airpublisher_creator_profiles
ALTER COLUMN creator_unique_identifier DROP NOT NULL;

-- Step 3: Add handles column if it doesn't exist
ALTER TABLE airpublisher_creator_profiles
ADD COLUMN IF NOT EXISTS handles TEXT NOT NULL DEFAULT '';

-- Step 4: Add profile_pic_url column if it doesn't exist  
ALTER TABLE airpublisher_creator_profiles
ADD COLUMN IF NOT EXISTS profile_pic_url TEXT;

-- Step 5: Remove Niche column if it exists (should use creator_profiles.niche instead)
ALTER TABLE airpublisher_creator_profiles
DROP COLUMN IF EXISTS "Niche";

-- Step 6: Ensure the trigger function exists to auto-generate creator_unique_identifier
CREATE OR REPLACE FUNCTION generate_creator_unique_identifier()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.creator_unique_identifier IS NULL THEN
    NEW.creator_unique_identifier := 'creator_' || SUBSTRING(NEW.user_id::text, 1, 8) || '_' || 
                                    TO_CHAR(EXTRACT(EPOCH FROM NOW())::bigint, 'FM999999999999') || '_' ||
                                    SUBSTRING(MD5(RANDOM()::text), 1, 8);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Step 7: Ensure the trigger exists
DROP TRIGGER IF EXISTS trigger_generate_creator_unique_identifier ON airpublisher_creator_profiles;
CREATE TRIGGER trigger_generate_creator_unique_identifier
  BEFORE INSERT ON airpublisher_creator_profiles
  FOR EACH ROW
  EXECUTE FUNCTION generate_creator_unique_identifier();

-- Step 8: Update comment
COMMENT ON TABLE airpublisher_creator_profiles IS 'AIR Publisher creator profile table. Stores AIR Publisher-specific fields (handles, profile_pic_url). Niche should come from creator_profiles table (shared schema) which references niches_list. creator_unique_identifier is auto-generated by trigger if not provided.';

